### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by Maslownumberone** [vorpalu/Huffman-Algorithm-GUI-App#2]
при вводе длинной строки закодированная строка не вмешается в форму
![image_2024-04-02_20-04-34](https://github.com/vorpalu/Huffman-Algorithm-GUI-App/assets/165780609/13b1e829-a9f2-43ea-935b-b2585fddc4b5)

**Comment by vorpalu** [comment]
Solved [7a6e874](https://github.com/vorpalu/Huffman-Algorithm-GUI-App/commit/7a6e8743e394d2c7d2fa307c4392964ed3bc638c)
